# Generated by Django 5.0.1 on 2024-02-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content2',
            field=models.TextField(default='test'),
        ),
    ]
