# Generated by Django 5.0.1 on 2024-02-02 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_content2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True, verbose_name='Número')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe')),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
            ],
        ),
    ]
