# Generated by Django 5.0.1 on 2024-02-02 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_formfactura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormFactura',
        ),
    ]
